{% set version = '0.1.1' %}

package:
  name: r-mervdown
  version: {{ version|replace("-", "_") }}

source:
  path: ../

build:
  number: 0
  skip: True  # [win]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - git

  host:
    - r-base  {{ r_base }}
    - r-rmarkdown

  run:
    - r-base
    - r-rmarkdown

test:
  commands:
    ## verify each template is draftable
    - $R -e "rmarkdown::draft('plyranges', 'plyranges', package='mervdown', edit=FALSE)"
    - $R -e "rmarkdown::draft('sce', 'sce', package='mervdown', edit=FALSE)"
    - $R -e "rmarkdown::draft('tidyverse', 'tidyverse', package='mervdown', edit=FALSE)"

about:
  home: https://github.com/mfansler/mervdown
  summary: A collection of opinionated R markdown templates the author created
    for scientific data analysis and reporting.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
